package notification_classes;

public enum NotificationCode {
    SUCCESS, ERROR, SIGN_IN, SIGN_UP, ADD_LIST, DELETE_LIST, CHANGE_LIST_NAME, SHARE_LIST, ADD_PRODUCT, DELETE_PRODUCT, CHANGE_QUANTITY, GROCERY_LIST, REFRESH_PRODUCTS, REFRESH_LISTS, CUSTOM_PRODUCT, GROCERY_INIT
}
